### ISSUE TITLE
Get test-suite to pass and documentation to build

### ISSUE THREAD

**Issue by m3wolf** [m3wolf/scimap#1]
This issue can be closed when you've pulled the latest source code and can get both the test-suite to pass and the documentation to build.

Instructions on all three of those things can be found here: https://scimap.readthedocs.io/en/latest/intro.html

The test-suite will make sure that you can run the existing code. The idea is that for every routine we write, we also write some code that calls that routine and checks that it does what we want or doesn't do what we don't want. That way we can feel confident that the python code we've written actually does what we think it does. An added benefit to having good tests is that when we make changes to the code, we can feel confident the we haven't broken something somewhere else, provided all the tests still pass.

If you run the test-suite and see "OK", then the tests all passed. You will see some "expected failures" as well; this is ok for now since we'll work on fixing those systematically. If you see any "failure" or "error" tests, the best plan is to paste the output into a gist and post a link to it as a comment below. Gists help avoid pasting large console output and cluttering up the conversation; they can be created here: https://gist.github.com/

The documentation is also something we should make sure we have up to date. Python includes a way to automatically build a website with the documentation; this gets uploaded to https://scimap.readthedocs.io whenever you push changes to the repository on github.

**Comment by brianmay19** [comment]
DONE!
